// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGRb2iOoglEMSs12ZTi2qXQeDXl-1UZNo',
    appId: '1:532565660515:web:396986050336dc244ff956',
    messagingSenderId: '532565660515',
    projectId: 'ho-pla',
    authDomain: 'ho-pla.firebaseapp.com',
    storageBucket: 'ho-pla.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCREjdb-Jzpn4g0uUIYzL3faarAbuYuUng',
    appId: '1:532565660515:android:7856cae2942d495e4ff956',
    messagingSenderId: '532565660515',
    projectId: 'ho-pla',
    storageBucket: 'ho-pla.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPV4ORj1nUtTVlohw5mcSriuhlOTEKJs0',
    appId: '1:532565660515:ios:842bcb98af14fd064ff956',
    messagingSenderId: '532565660515',
    projectId: 'ho-pla',
    storageBucket: 'ho-pla.appspot.com',
    iosBundleId: 'tech.hopla.hoPla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPV4ORj1nUtTVlohw5mcSriuhlOTEKJs0',
    appId: '1:532565660515:ios:9aed4bb6094874454ff956',
    messagingSenderId: '532565660515',
    projectId: 'ho-pla',
    storageBucket: 'ho-pla.appspot.com',
    iosBundleId: 'tech.hopla.hoPla.RunnerTests',
  );
}
